services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $maskExtensionConfiguration: '@extensionconfiguration.mask'

  NH\MaskToContentBlocks\:
    resource: '../Classes/*'
